name: Node.js CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 

    - name: Install dependencies
      run: npm install
        
    - name: Display .env file
      run: |
        echo "DB_USER=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        echo "DB_NAME=Assignment-3" >> .env
        echo "PORT=3000" >> .env
        cat .env

    - name: Start MySQL Server
      run: |
       sudo service mysql start
       sleep 10

    - name: Check MySQL Server Status
      run: |
      # Start MySQL server
      sudo service mysql start
      # Wait for MySQL server to fully start (adjust the sleep time as needed)
      sleep 10



    
  

