name: Node.js CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 

    - name: Install dependencies
      run: npm install

    - name: Install MySQL Client
      run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-client

    - name: Set up MySQL Database
      env:
        DB_HOST: localhost
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: Assignment-3
      run: |
        mysql -u $DB_USER -p$DB_PASSWORD 
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-client

    - name: Set up MySQL Database
      env:
        DB_HOST: localhost
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: Assignment-3
      run: |
        mysql -u $DB_USER -p$DB_PASSWORD 
