name: Node.js CI

on:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  build:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World!"

