name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 

    - name: Install dependencies
      run: npm install
        
    - name: Display .env file
      run: |
        echo "DB_USER=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        echo "DB_NAME=Assignment3" >> .env
        echo "PORT=3000" >> .env
        cat .env
       
    - name: configuremysql
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        sudo systemctl start mysql
        sudo systemctl status mysql
        DEFAULT_PASS=$(sudo cat ../../var/log/mysqld.log | grep "A temporary password" | awk '{print $13}')

        echo %DEFAULT_PASS%
        
        yes | sudo yum install expect

        SECURE_MYSQL=$(expect -c "

          set timeout 10
          spawn sudo mysql -u root -p

          expect \"Enter password:\"
          send \"$DEFAULT_PASS\r\"

          expect \"mysql>\"
          send \"ALTER USER 'root'@'localhost' IDENTIFIED BY 'Abcde@12345';\r\"

          expect \"mysql>\"
          send \"CREATE DATABASE webapp2;\r\"

          expect \"mysql>\"
          send \"exit\r\"

          expect eof
          ")

        echo "$SECURE_MYSQL"
        mysql -u root -p"${{secrets.MY_SQL_PASSWORD}}" -e "CREATE DATABASE Assignment3;"

    
    - name: Run Tests
      run : npm test
    

# checking CI command on PR - 1,2













    
  

