name: Node.js CI

on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 

    - name: Install dependencies
      run: npm install

    - name: Set up MySQL
      run: |
        sudo apt-get -y update
        sudo apt-get -y install mysql-server
        sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'root';"
        sudo mysql -u root -e "CREATE DATABASE Assignment-3;"
        sudo mysql -u root -e "GRANT ALL PRIVILEGES ON Assignment-3.* TO 'root'@'localhost';"
        echo "DB_USER=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        echo "DB_NAME=Assignment-3" >> .env
        echo "PORT=3000" >> .env

    - name: Display .env file
      run: cat .env

    
  

